CREATE TABLE IF NOT EXISTS USER
(
	USER_ID int(11) AUTO_INCREMENT NOT NULL,
	LOGIN_ID varchar(32) DEFAULT NULL,
	FIRST_NAME varchar(30) NOT NULL,
	LAST_NAME varchar(30) NOT NULL,
	DESIGNATION varchar(64) NOT NULL,
	DEPT_ID int(11) NOT NULL,
	MOBILE varchar(16) NOT NULL,
	EMAIL varchar(120) NOT NULL,
	STATUS tinyint DEFAULT 0,
	CREATE_DATE timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS ADDRESS
(
	ADDRESS_ID int(11) NOT NULL,
	ADDRESS varchar(255) NOT NULL,
	CITY varchar(255) NOT NULL,
	COUNTRY varchar(255)NOT NULL,
	POST_CODE int(11) NOT NULL,
	USER_ID int(11) NOT NULL,
	PRIMARY KEY(ADDRESS_ID)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT
(
	DEPT_ID int(11) NOT NULL,
	DEPT_NAME varchar(255) NOT NULL,
	PRIMARY KEY(DEPT_ID)
);

CREATE TABLE IF NOT EXISTS USER_ROLE
(
	ROLE_ID int(11) NOT NULL,
	USER_TYPE varchar(120)  NOT NULL,
	USER_ID int(11) NOT NULL,
	PRIMARY KEY(ROLE_ID)
);

ALTER TABLE USER 
	ADD CONSTRAINT FK_USER FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID);
ALTER TABLE ADDRESS
	 ADD CONSTRAINT FK_ADDRESS FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
ALTER TABLE USER_ROLE
	 ADD CONSTRAINT FK_USER_ROLE FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);



